name: FreedomBot
main: com.mcplugindev.freedombot.FreedomBot
version: 2.3
description: 'FreedomBot is a plugin that will help you with moderating your FreeOp server.'
author: FoxIshDaBest
authors: [DUFC_Liam, _JustYellow, tylerhyperHD]
softdepend: [TotalFreedomMod]

commands:
    freedombot:
      description: 'Displays FreedomBot information.'
      usage: /<command>
      
    cleanup:
      description: 'Cleanup command.'
      usage: /<command>
      
    opme:
      description: 'Op yourself.'
      usage: /<command>
      
    adminalert:
      description: 'Alert an online administrator.'
      usage: /<command>
    
    admintools:
        description: 'Gives yourself administrator tools.'
        usage: /<command>
