name: FreedomBot
main: com.mcplugindev.freedombot.FreedomBot
version: 2.3pre-2
description: 'FreedomBot is a plugin that will help you with moderating your FreeOp server.'
author: FoxIshDaBest
authors: [DUFC_Liam, _JustYellow, tylerhyperHD]
softdepend: [TotalFreedomMod]

commands:
    freedombot:
      description: 'Displays FreedomBot information.'
      usage: /<command>
      
    admintool:
      description: 'Administrator tools.'
      usage: /<command>
      
    opme:
      description: 'Op yourself.'
      usage: /<command>
      
    adminalert:
      description: 'Alert an online administrator.'
      usage: /<command>
